version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.16

    ports:
    - 8888:80

    environment: 
      PGADMIN_DEFAULT_EMAIL: roemhildtg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
volumes:
  db:
    driver: local