host: localhost
port: 3030
public: ./public/
origins:
  - http://localhost:3030
paginate:
  default: 10
  max: 50
postgresql:
  client: pg
  connection: postgres://postgres:@localhost:5432/feathers-tasks
authentication:
  entity: user
  service: users
  secret: lBLzaXtgpLQLa5FLoGil/XO6jYY5t6wZ
  authStrategies:
    - jwt
    - local
  jwtOptions:
    header:
      typ: access
    audience: https://yourdomain.com
    algorithm: HS256
    expiresIn: 1d
  local:
    usernameField: email
    passwordField: password
